# Generated by Django 2.2.19 on 2022-02-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20220115_1319"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
    ]
